server:
  port: 8080
spring:
  datasource:
#    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/AwsServer?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/AwsServer?allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    mail:
      default-encoding: UTF-8
      host: smtp.gmail.com
      port: 587
      username: testdisk1110@gmail.com
      password: "lcbk silq oexu laom"
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
    redis:
      data:
        host: 54.180.103.113
        port: 6379

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # 개발 환경에서는 'update', 운영 환경에서는 'validate' 또는 'none' 권장
    show-sql: true
logging:
  level:
    org.hibernate: info
    org.springframework: info
jwt:
  secret: jHkb4lgNCk/N2GJ7Jx08To+7duFpeVQ6uoEbdy23Panf+hWKarPu5z9uDwKORftpJ2kRRcI+0+wpUaYKzXod7w==
  access-token-validity-in-seconds: 1800 # 30분
  refresh-token-validity-in-seconds: 604800 # 7일
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html