name: CI/CD using github actions & docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
  MYSQL_DB_URL: ${{ secrets.MYSQL_DB_URL }}
  # REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
  # REDIS_DB_URL: ${{ secrets.REDIS_DB_URL }}
  JWT_KEY: ${{ secrets.JWT_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: set chmod
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKERHUB_ID }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t server10 . # Dockerfile 경로 수정
          docker tag server10 ${{ secrets.DOCKERHUB_ID }}/server10:latest
          docker push ${{ secrets.DOCKERHUB_ID }}/server10:latest

      - name: Deploy with SSH
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }} 
          port: ${{ secrets.PORT }} 
          envs: GITHUB_SHA
          script: |
            script: |
            docker login -u ${{ secrets.DOCKERHUB_ID }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker stop server10
            docker rm server10
            docker network disconnect redis-network server10
            docker rmi ${{ secrets.DOCKERHUB_ID }}/server10:latest
            docker pull ${{ secrets.DOCKERHUB_ID }}/server10:latest
            docker run -d -p 80:8080 --env-file ./server.env --name server10 ${{ secrets.DOCKERHUB_ID }}/server10:latest

  deploy:

    runs-on: ubuntu-latest
    permissions: write-all
    needs: build

    steps:
      - uses: actions/checkout@v3
