name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_PUBLIC_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            PID=$(lsof -t -i:8080)
            if [ -z "$PID" ]; then
              echo "No process running on port 8080"
            else
              echo "Killing process $PID"
              kill -9 $PID
            fi

            cd ~/app
            git pull origin main
            chmod +x ./gradlew
            ./gradlew clean build

            cd build/libs
            nohup java -jar Server10-0.0.1-SNAPSHOT.jar > ~/server10/nohup.out 2>&1 &
