name: deploy

on:
  push:
    branches:
      - master

jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: ssh to ec2
        uses: appleboy/ssh-action@v0.1.5
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_PUBLIC_HOST }} 
          username: ${{ secrets.SSH_USERNAME }} 
          script: |
            PID=$(lsof -t -i:8080)
            if [ -z "$PID" ]; then
              echo "No process is running on port 8080"
            else
              echo "Killing process $PID"
              kill -9 $PID
            fi
            
            cd ~/server10  
            git pull
            

            chmod +x gradlew
            ./gradlew build
            
            # 빌드된 JAR 파일 실행
            cd build/libs
            nohup java -jar Server10-0.0.1-SNAPSHOT.jar > ~/server10/nohup.out 2>&1 &
