name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Java 17을 설치
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    # gradlew 실행 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    # Spring Boot 어플리케이션 Build
    - name: Build with Gradle
      run: ./gradlew clean build --exclude-task test

    # EC2로 파일 전송 및 배포
    - name: Deploy to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_PUBLIC_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "build/libs/*.jar"
        target: "/home/ec2-user/app/"

    - name: Restart application on EC2
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SSH_PUBLIC_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          pkill -f 'java -jar' || true
          nohup java -jar ~/Desktop/Server10-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
